### ISSUE TITLE
vocabulary fix

### ISSUE THREAD

**Issue by HellCatVN** [xluffy/xluffy.github.io#1]
https://xluffy.github.io/post/how-to-hash-store-password/ 
Chào bạn mình có đọc về bài viết của bạn và thấy rất hay tui nhiên vẫn còn lỗi chính tả nhỏ mong bạn khắc phục sớm để bài viết chuyên nghiệp hơn nè ^^
 brute-force attach, dictionary attach ->attack nhen 🥉

**Comment by xluffy** [comment]
Cám ơn bạn, không hiểu sao giờ mình mới thấy comment này.
