### ISSUE TITLE
Cách băm mật khẩu

### ISSUE THREAD

**Issue by tackelua** [xluffy/xluffy.github.io#2]
Cách băm mật khẩu như bài viết bạn nói là hash ở server side.
Mình có ý là tại sao chúng ta ko hash nhẹ password trước ở client rồi lên server hash tiếp với salt và pepper. Như vậy password gửi lên server sẽ ko còn plain text, thêm một tầng bảo mật nữa.
Bạn nghĩ sao về ý tưởng này?

**Comment by xluffy** [comment]
Có 2 vấn đề

1. Bạn `hash` ở client thì lên server, server không cách gì để de-hash, biết được real-password để check/compare được
2. Đã có SSL để giải quyết vấn đề encrypt password rồi.
